spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc

    #jdbc:
     # initialize-schema: never
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3360/quartz?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 1234
      max-active: 100
      max-wait: 10000
      initial-size: 5
      min-idle: 10
      filters: stat,wall,slf4j
      filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 2000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
server:
  port: 8083
mybatis-plus:
  check-config-location: true
  mapperLocations: classpath:/mapper/*.xml
  typeAliasesPackage: com.sofmit.entity
  global-config:
    db-config:
      id-type: UUID
      field-strategy: not_empty
      column-underline: true
      capital-mode: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: true
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false